{{ if and .Values.gateway.enabled (eq .Values.gateway.gatewayClassName "kgateway") .Values.gateway.gatewayParameters.enabled }}
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: {{ include "gateway.fullname" . }}
  labels: {{ include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/gateway: {{ include "gateway.fullname" . }}
    app.kubernetes.io/component: inference-gateway
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.gateway.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.gateway.annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  kube:
    envoyContainer:
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      bootstrap:
        componentLogLevels:
          upstream: {{ .Values.gateway.gatewayParameters.logLevel }}
          http: {{ .Values.gateway.gatewayParameters.logLevel }}
          connection: {{ .Values.gateway.gatewayParameters.logLevel }}
        logLevel: info # keep as info for everything else, the other debug levels will be sufficient if more logging needed
      {{- if .Values.gateway.gatewayParameters.resources }}
      resources: {{ .Values.gateway.gatewayParameters.resources | toYaml | nindent 8 }}
      {{- end}}
    service:
      type: {{ .Values.gateway.serviceType | default "NodePort" | quote }}
      extraLabels:
        gateway: custom
    podTemplate:
      extraLabels:
        gateway: custom
    floatingUserId: true
    sdsContainer:
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        seccompProfile:
          type: RuntimeDefault
{{- end}}
