gateway:
  gatewayClassName: istio
  gatewayParameters:
    logLevel: error
    resources:
      limits:
        cpu: "4"
        memory: 4Gi
      requests:
        cpu: "1"
        memory: 1Gi
  destinationRule:
    enabled: true
    host: ms-wide-ep-llm-d-modelservice-epp.llm-d-wide-ep.svc.cluster.local
    trafficPolicy:
      connectionPool:
        http:
          http1MaxPendingRequests: 256000
          maxRequestsPerConnection: 256000
          http2MaxRequests: 256000
          idleTimeout: "900s"
        tcp:
          maxConnections: 256000
          maxConnectionDuration: "1800s"
          connectTimeout: "900s"
      tls:
        mode: SIMPLE
        insecureSkipVerify: true
