name: Helm Chart Release

on:
  push:
    branches:
      - main
    paths:
      - charts/**

  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # Checks out the main branch
        ref: main
        fetch-depth: 0
        persist-credentials: false

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Add Helm dependency repos
      run: |
        for dir in $(ls -d charts/*/); do
          helm dependency list  --max-col-width 120 $dir 2> /dev/null | tail +2 | head -n -1 | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done
        done

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f # v1.7.0
      env:
        CR_TOKEN: "${{ secrets.CR_PAT }}"
        CR_RELEASE_NAME_TEMPLATE: "{{ .Version }}"
        CR_SKIP_EXISTING: "true"
